import React from 'react';
import { Link } from 'react-router-dom';

const S = {
  page: { minHeight:'100vh', background:'#030712' },
  nav: {
    borderBottom:'1px solid rgba(31,41,55,0.8)',
    background:'rgba(3,7,18,0.9)', backdropFilter:'blur(8px)',
    position:'sticky', top:0, zIndex:40,
  },
  navInner: {
    maxWidth:'80rem', margin:'0 auto', padding:'0 1.5rem',
    height:'4rem', display:'flex', alignItems:'center', justifyContent:'space-between',
  },
  logo: { display:'flex', alignItems:'center', gap:'0.625rem', textDecoration:'none' },
  logoBadge: {
    width:32, height:32, background:'#4f46e5', borderRadius:'0.625rem',
    display:'flex', alignItems:'center', justifyContent:'center',
    fontWeight:700, color:'#fff', fontSize:'1rem',
  },
  logoText: { color:'#fff', fontWeight:700, fontSize:'1.125rem' },
  navLinks: { display:'flex', alignItems:'center', gap:'0.75rem' },
  hero: {
    maxWidth:'80rem', margin:'0 auto', padding:'5rem 1.5rem 6rem',
    textAlign:'center', position:'relative',
  },
  pill: {
    display:'inline-flex', alignItems:'center', gap:'0.5rem',
    background:'rgba(99,102,241,0.1)', border:'1px solid rgba(99,102,241,0.2)',
    borderRadius:'9999px', padding:'0.375rem 1rem',
    fontSize:'0.875rem', color:'#a5b4fc', marginBottom:'2rem',
  },
  dot: { width:6, height:6, background:'#818cf8', borderRadius:'50%', animation:'pulse 2s infinite' },
  h1: {
    fontSize:'clamp(2rem, 5vw, 3.75rem)', fontWeight:800, color:'#fff',
    lineHeight:1.1, marginBottom:'1.5rem', maxWidth:'56rem', margin:'0 auto 1.5rem',
  },
  grad: { background:'linear-gradient(135deg,#818cf8,#a78bfa)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent' },
  sub: {
    color:'#9ca3af', fontSize:'1.125rem', maxWidth:'36rem',
    margin:'0 auto 2.5rem', lineHeight:1.7,
  },
  btnRow: { display:'flex', gap:'1rem', justifyContent:'center', flexWrap:'wrap', marginBottom:'3rem' },
  statsRow: {
    display:'flex', gap:'2rem', justifyContent:'center', flexWrap:'wrap',
    color:'#9ca3af', fontSize:'0.875rem',
  },
  statItem: { display:'flex', alignItems:'center', gap:'0.5rem' },
  section: { maxWidth:'80rem', margin:'0 auto', padding:'4rem 1.5rem' },
  sectionTitle: { fontSize:'1.875rem', fontWeight:700, color:'#fff', marginBottom:'1rem', textAlign:'center' },
  sectionSub: { color:'#9ca3af', textAlign:'center', marginBottom:'3rem', maxWidth:'32rem', margin:'0 auto 3rem' },
  featureGrid: { display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))', gap:'1.5rem' },
  featureCard: {
    background:'rgba(17,24,39,0.6)', border:'1px solid #1f2937',
    borderRadius:'1rem', padding:'1.5rem', transition:'border-color 0.2s',
  },
  featureIcon: { fontSize:'2rem', marginBottom:'1rem', display:'block' },
  featureTitle: { color:'#fff', fontWeight:600, fontSize:'1.05rem', marginBottom:'0.5rem' },
  featureDesc: { color:'#9ca3af', fontSize:'0.875rem', lineHeight:1.6 },
  twoCol: {
    display:'grid', gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',
    gap:'4rem', alignItems:'center',
  },
  previewBox: {
    background:'rgba(17,24,39,0.6)', border:'1px solid #1f2937',
    borderRadius:'1.5rem', padding:'1.5rem',
  },
  previewHeader: { display:'flex', alignItems:'center', gap:'0.75rem', marginBottom:'1.5rem' },
  moduleRow: { marginBottom:'1rem' },
  modLabel: { display:'flex', justifyContent:'space-between', fontSize:'0.875rem', marginBottom:'0.375rem' },
  modBar: { height:6, background:'#1f2937', borderRadius:9999, overflow:'hidden' },
  ctaBox: {
    background:'linear-gradient(135deg,rgba(49,46,129,0.4),rgba(88,28,135,0.3))',
    border:'1px solid rgba(99,102,241,0.2)', borderRadius:'2rem',
    padding:'4rem 2rem', textAlign:'center',
  },
  footer: {
    borderTop:'1px solid rgba(31,41,55,0.5)', padding:'2rem 1.5rem',
    textAlign:'center', color:'#4b5563', fontSize:'0.875rem',
  },
};

const FEATURES = [
  { icon:'🗺️', title:'Structured Roadmaps', desc:'Follow curated learning paths from beginner to advanced for popular developer roles and programming languages.' },
  { icon:'🤖', title:'AI-Generated Notes', desc:'Get instant, detailed lesson notes generated by GPT with deep explanations, code examples, and best practices.' },
  { icon:'📈', title:'Progress Tracking', desc:'Mark lessons complete, track your percentage, and visualize your learning journey with beautiful progress bars.' },
  { icon:'🎯', title:'Personalized Goals', desc:'Set your career goal and experience level. The platform tailors content and recommendations to your journey.' },
  { icon:'⚡', title:'AI Custom Roadmaps', desc:'Describe your learning goal and let AI generate a custom, structured roadmap just for you in seconds.' },
  { icon:'📚', title:'Curated Resources', desc:'Every lesson includes hand-picked articles, videos, and official docs links to accelerate your learning.' },
];

const MODULES = [
  { name:'Web Fundamentals', lessons:3, pct:100 },
  { name:'JavaScript Core',  lessons:3, pct:67  },
  { name:'React.js',         lessons:3, pct:0   },
  { name:'Advanced Frontend',lessons:2, pct:0   },
];

function Home() {
  return (
    <div style={S.page}>
      {/* Navbar */}
      <nav style={S.nav}>
        <div style={S.navInner}>
          <Link to="/" style={S.logo}>
            <div style={S.logoBadge}>L</div>
            <span style={S.logoText}>LearnPath</span>
          </Link>
          <div style={S.navLinks}>
            <Link to="/login" className="btn-ghost">Sign in</Link>
            <Link to="/register" className="btn-primary">Get Started Free</Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <div style={{ background:'radial-gradient(ellipse at 50% 0%,rgba(99,102,241,0.08),transparent 60%)' }}>
        <div style={S.hero}>
          <div style={S.pill}>
            <div style={S.dot} />
            AI-Powered Learning Roadmaps
          </div>
          <h1 style={S.h1}>
            Your personalized path to<br />
            <span style={S.grad}>becoming a developer</span>
          </h1>
          <p style={S.sub}>
            Get structured, AI-generated learning roadmaps for any programming role or language.
            Track progress and stay on track with personalized recommendations.
          </p>
          <div style={S.btnRow}>
            <Link to="/register" className="btn-primary" style={{ padding:'0.75rem 2rem', fontSize:'1rem' }}>
              Start Learning Free →
            </Link>
            <Link to="/login" className="btn-secondary" style={{ padding:'0.75rem 2rem', fontSize:'1rem' }}>
              Sign In
            </Link>
          </div>
          <div style={S.statsRow}>
            {[['5+','Career Roadmaps'],['50+','Lessons'],['AI','Powered Notes'],['Free','To Get Started']].map(([v,l])=>(
              <div key={l} style={S.statItem}>
                <strong style={{color:'#fff'}}>{v}</strong> {l}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Features */}
      <div style={S.section}>
        <h2 style={S.sectionTitle}>Everything you need to level up</h2>
        <p style={S.sectionSub}>A complete learning platform with AI assistance, structured roadmaps, and progress tracking.</p>
        <div style={S.featureGrid}>
          {FEATURES.map(f=>(
            <div key={f.title} style={S.featureCard}
              onMouseEnter={e=>e.currentTarget.style.borderColor='rgba(99,102,241,0.4)'}
              onMouseLeave={e=>e.currentTarget.style.borderColor='#1f2937'}
            >
              <span style={S.featureIcon}>{f.icon}</span>
              <h3 style={S.featureTitle}>{f.title}</h3>
              <p style={S.featureDesc}>{f.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Roadmap preview */}
      <div style={S.section}>
        <div style={S.twoCol}>
          <div>
            <h2 style={{fontSize:'1.875rem',fontWeight:700,color:'#fff',marginBottom:'1rem'}}>Choose your learning path</h2>
            <p style={{color:'#9ca3af',marginBottom:'2rem',lineHeight:1.7}}>From frontend to backend, Python to JavaScript — structured roadmaps for every popular developer role and language.</p>
            <div style={{display:'flex',flexDirection:'column',gap:'0.75rem'}}>
              {[['🎨','Frontend Developer','#f59e0b',14,'Role'],
                ['⚙️','Backend Developer','#10b981',10,'Role'],
                ['🐍','Python Programming','#3b82f6',11,'Language'],
                ['📊','Data Scientist','#8b5cf6',8,'Role'],
                ['💛','JavaScript Mastery','#eab308',8,'Language'],
              ].map(([icon,name,color,n,type])=>(
                <div key={name} style={{
                  background:'rgba(17,24,39,0.4)', border:'1px solid #1f2937',
                  borderRadius:'0.75rem', padding:'0.75rem 1rem',
                  display:'flex', alignItems:'center', gap:'0.75rem',
                }}>
                  <div style={{
                    width:36,height:36, borderRadius:'0.5rem',
                    background:color+'20', display:'flex',alignItems:'center',justifyContent:'center', fontSize:'1.1rem',
                  }}>{icon}</div>
                  <div style={{flex:1}}>
                    <p style={{color:'#fff',fontWeight:500,fontSize:'0.875rem'}}>{name}</p>
                    <p style={{color:'#6b7280',fontSize:'0.75rem'}}>{n} lessons · {type}</p>
                  </div>
                  <div style={{width:8,height:8,borderRadius:'50%',background:color}} />
                </div>
              ))}
            </div>
          </div>
          <div style={S.previewBox}>
            <div style={S.previewHeader}>
              <div style={{width:44,height:44,background:'rgba(245,158,11,0.15)',borderRadius:'0.75rem',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'1.5rem'}}>🎨</div>
              <div>
                <p style={{color:'#fff',fontWeight:600}}>Frontend Developer</p>
                <p style={{color:'#6b7280',fontSize:'0.875rem'}}>4 Modules · 14 Lessons</p>
              </div>
            </div>
            {MODULES.map(m=>(
              <div key={m.name} style={S.moduleRow}>
                <div style={S.modLabel}>
                  <span style={{color:'#d1d5db'}}>{m.name}</span>
                  <span style={{color:'#6b7280'}}>{m.lessons} lessons</span>
                </div>
                <div style={S.modBar}>
                  <div style={{height:'100%',background:'linear-gradient(to right,#f59e0b,#f97316)',width:`${m.pct}%`,transition:'width 1s ease'}} />
                </div>
              </div>
            ))}
            <div style={{marginTop:'1rem',paddingTop:'1rem',borderTop:'1px solid #1f2937',display:'flex',justifyContent:'space-between',alignItems:'center'}}>
              <span style={{color:'#9ca3af',fontSize:'0.875rem'}}>Overall Progress</span>
              <span style={{color:'#f59e0b',fontWeight:600}}>35%</span>
            </div>
          </div>
        </div>
      </div>

      {/* CTA */}
      <div style={S.section}>
        <div style={S.ctaBox}>
          <h2 style={{fontSize:'1.875rem',fontWeight:700,color:'#fff',marginBottom:'1rem'}}>Ready to start your journey?</h2>
          <p style={{color:'#9ca3af',marginBottom:'2rem',maxWidth:'32rem',margin:'0 auto 2rem'}}>Join developers using LearnPath to build structured, AI-assisted learning habits.</p>
          <Link to="/register" className="btn-primary" style={{padding:'0.75rem 2.5rem',fontSize:'1rem'}}>
            Create Free Account →
          </Link>
        </div>
      </div>

      <footer style={S.footer}>
        © 2024 LearnPath · Built with React, Node.js, MongoDB & OpenAI
      </footer>
    </div>
  );
}

export default Home;